bot-settings:
  move-speed: 0.25
  bhop: false
  idle: false
  idle-radius: 15
  combat: true
  revenge: true
  auto-target: true
  criticals: true
  target-players: true
  target-mobs: false
  target-bots: true
  attack-cooldown: 12
  melee-range: 3.0
  prefer-sword: true
  ranged: true
  mace: true
  ranged-min-range: 3.0
  ranged-optimal-range: 10.0
  ranged-max-range: 20.0
  bow-draw-ticks: 20
  arrow-prediction: true
  ranged-strafe: true
  ranged-retreat: true
  auto-shield: true
  shield-break: true
  shield-break-chance: 30
  shield-hold-ticks: 60
  shield-raise-ticks: 5
  shield-mace: true
  auto-armor: true
  auto-weapon: true
  auto-eat: true
  auto-potion: true
  auto-mend: true
  auto-totem: true
  totem-priority: false
  miss-chance: 5
  mistake-chance: 5
  aim-speed: 15.0
  show-in-tab: true
  bot-leave-on-death: false
