name: PvPBot
version: ${version}
main: com.pvpbot.PvPBotPlugin
api-version: '1.21'
depend:
  - ProtocolLib
  - Citizens
commands:
  pvpbot:
    description: Main PvPBot command
    usage: /<command> <spawn|remove|removeall> [name]
    permission: pvpbot.admin
permissions:
  pvpbot.admin:
    description: Allows use of /pvpbot commands
    default: op
